compile:
    ext: html
    out_dir: compiled
    src_dir: src
context:
    navs:
      - filename: index
        name: blog
        url: /
      - filename: resume
        name: resume
        url: /resume.html
    year: 2017
