baseURL = "http://moomou.io/"
languageCode = "en-us"
title = "moomou"
theme = "hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://github.com/moomou\" target=\"_blank\">Github</a>"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "lorem"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "paul mou"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/moomou"
fa_icon = "fa-github"
